[tool.poetry]
name = "generate-waveforms"
version = "0.1.0"
description = "Project for generating a waveform dataset of arbitrary morphology"
authors = ["ethan.marx <ethan.marx@ligo.org>"]
license = "MIT"
readme = "README.md"
packages = [{include = "generate_waveforms"}]

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
