# define filters for file changes
# to trigger unit tests

# filter for changes
# to workflow
workflow: &workflow
  - '.github/filters.yaml'
  - '.github/workflows/ci-tests.yaml'

# libraries
libs/injection/:
  - *workflow
  - 'libs/injection/**'

libs/architectures/:
  - *workflow
  - 'libs/architectures/**'

libs/trainer/:
  - *workflow
  - 'libs/trainer/**'


# projects
projects/sandbox/generate_waveforms/:
  - *workflow
  - 'projects/sandbox/generate_waveforms/**'
  - 'libs/injection/**'
