# define filters for file changes
# to trigger unit tests

# filter for changes
# to workflow
workflow: &workflow
  - '.github/filters.yaml'
  - '.github/workflows/ci-tests.yaml'

# libraries
libs/injection/:
  - *workflow
  - 'libs/injection/**'
  - 'libs/base/**'

libs/architectures/:
  - *workflow
  - 'libs/architectures/**'
  
libs/trainer/:
  - *workflow
  - 'libs/trainer/**'
  - 'libs/architectures/**'
  - 'libs/data/**'

libs/data/:
  - *workflow
  - 'libs/data/**'
  - 'ml4gw/**'
  - 'libs/base/**'

# projects
projects/sandbox/data_generation/:
  - *workflow
  - 'ml4gw/**'
  - 'projects/sandbox/data_generation/**'
  - 'libs/injection/**'



# projects/sandbox/generate_background/:
#  - *workflow
#  - 'projects/sandbox/generate_background/**'

# projects/sandbox/train/:
#  - *workflow
#  - 'projects/sandbox/train/**'
#  - 'ml4gw/**'
#  - 'libs/data/**'
