[tool.poetry]
name = "mlpe"
version = "0.1.0"
description = "Parameter estimation for gravitational wave sources"
authors = ["ethan.marx <ethan.marx@ligo.org>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.10"

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.16"

[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.tox
  | _build
  | dist
  | docs
)/
'''

[tool.isort]
known_first_party = ["bbhnet"]
multi_line_output = 3
include_trailing_comma = true

[build-system]
requires = ["poetry>=1.2"]
build-backend = "poetry.masonry.api"

